import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "entity_pages" ADD COLUMN "canonical_url" varchar;
  ALTER TABLE "entity_pages" ADD COLUMN "human_approval_approval_timestamp" timestamp(3) with time zone;
  ALTER TABLE "entity_pages" ADD COLUMN "human_approval_approver" varchar;
  ALTER TABLE "entity_pages" ADD COLUMN "human_approval_approver_limitation" varchar;
  ALTER TABLE "entity_pages" ADD COLUMN "human_approval_content_revision_hash" varchar;
  ALTER TABLE "entity_pages" ADD COLUMN "human_approval_publication_revision_hash" varchar;
  ALTER TABLE "entity_pages" ADD COLUMN "human_approval_supporting_approved_insight_ids" jsonb;
  ALTER TABLE "entity_pages" ADD COLUMN "human_approval_validation_result_deterministic_hard_gates_passed" boolean;
  ALTER TABLE "entity_pages" ADD COLUMN "human_approval_validation_result_semantic_quality_passed" boolean;
  ALTER TABLE "entity_pages" ADD COLUMN "human_approval_validation_result_failure_codes" jsonb;
  ALTER TABLE "entity_pages" ADD COLUMN "human_approval_publication_scope_approved_canonical_paths" jsonb;
  ALTER TABLE "entity_pages" ADD COLUMN "human_approval_publication_scope_excluded_draft_ids" jsonb;
  ALTER TABLE "entity_pages" ADD COLUMN "human_approval_publication_scope_deployment_authorized" boolean;
  ALTER TABLE "entity_pages" ADD COLUMN "human_approval_publication_scope_publication_authorized" boolean;
  ALTER TABLE "pillar_pages" ADD COLUMN "canonical_url" varchar;
  ALTER TABLE "pillar_pages" ADD COLUMN "human_approval_approval_timestamp" timestamp(3) with time zone;
  ALTER TABLE "pillar_pages" ADD COLUMN "human_approval_approver" varchar;
  ALTER TABLE "pillar_pages" ADD COLUMN "human_approval_approver_limitation" varchar;
  ALTER TABLE "pillar_pages" ADD COLUMN "human_approval_content_revision_hash" varchar;
  ALTER TABLE "pillar_pages" ADD COLUMN "human_approval_publication_revision_hash" varchar;
  ALTER TABLE "pillar_pages" ADD COLUMN "human_approval_supporting_approved_insight_ids" jsonb;
  ALTER TABLE "pillar_pages" ADD COLUMN "human_approval_validation_result_deterministic_hard_gates_passed" boolean;
  ALTER TABLE "pillar_pages" ADD COLUMN "human_approval_validation_result_semantic_quality_passed" boolean;
  ALTER TABLE "pillar_pages" ADD COLUMN "human_approval_validation_result_failure_codes" jsonb;
  ALTER TABLE "pillar_pages" ADD COLUMN "human_approval_publication_scope_approved_canonical_paths" jsonb;
  ALTER TABLE "pillar_pages" ADD COLUMN "human_approval_publication_scope_excluded_draft_ids" jsonb;
  ALTER TABLE "pillar_pages" ADD COLUMN "human_approval_publication_scope_deployment_authorized" boolean;
  ALTER TABLE "pillar_pages" ADD COLUMN "human_approval_publication_scope_publication_authorized" boolean;
  ALTER TABLE "cluster_pages" ADD COLUMN "canonical_url" varchar;
  ALTER TABLE "cluster_pages" ADD COLUMN "human_approval_approval_timestamp" timestamp(3) with time zone;
  ALTER TABLE "cluster_pages" ADD COLUMN "human_approval_approver" varchar;
  ALTER TABLE "cluster_pages" ADD COLUMN "human_approval_approver_limitation" varchar;
  ALTER TABLE "cluster_pages" ADD COLUMN "human_approval_content_revision_hash" varchar;
  ALTER TABLE "cluster_pages" ADD COLUMN "human_approval_publication_revision_hash" varchar;
  ALTER TABLE "cluster_pages" ADD COLUMN "human_approval_supporting_approved_insight_ids" jsonb;
  ALTER TABLE "cluster_pages" ADD COLUMN "human_approval_validation_result_deterministic_hard_gates_passed" boolean;
  ALTER TABLE "cluster_pages" ADD COLUMN "human_approval_validation_result_semantic_quality_passed" boolean;
  ALTER TABLE "cluster_pages" ADD COLUMN "human_approval_validation_result_failure_codes" jsonb;
  ALTER TABLE "cluster_pages" ADD COLUMN "human_approval_publication_scope_approved_canonical_paths" jsonb;
  ALTER TABLE "cluster_pages" ADD COLUMN "human_approval_publication_scope_excluded_draft_ids" jsonb;
  ALTER TABLE "cluster_pages" ADD COLUMN "human_approval_publication_scope_deployment_authorized" boolean;
  ALTER TABLE "cluster_pages" ADD COLUMN "human_approval_publication_scope_publication_authorized" boolean;
  ALTER TABLE "frameworks" ADD COLUMN "canonical_url" varchar;
  ALTER TABLE "frameworks" ADD COLUMN "human_approval_approval_timestamp" timestamp(3) with time zone;
  ALTER TABLE "frameworks" ADD COLUMN "human_approval_approver" varchar;
  ALTER TABLE "frameworks" ADD COLUMN "human_approval_approver_limitation" varchar;
  ALTER TABLE "frameworks" ADD COLUMN "human_approval_content_revision_hash" varchar;
  ALTER TABLE "frameworks" ADD COLUMN "human_approval_publication_revision_hash" varchar;
  ALTER TABLE "frameworks" ADD COLUMN "human_approval_supporting_approved_insight_ids" jsonb;
  ALTER TABLE "frameworks" ADD COLUMN "human_approval_validation_result_deterministic_hard_gates_passed" boolean;
  ALTER TABLE "frameworks" ADD COLUMN "human_approval_validation_result_semantic_quality_passed" boolean;
  ALTER TABLE "frameworks" ADD COLUMN "human_approval_validation_result_failure_codes" jsonb;
  ALTER TABLE "frameworks" ADD COLUMN "human_approval_publication_scope_approved_canonical_paths" jsonb;
  ALTER TABLE "frameworks" ADD COLUMN "human_approval_publication_scope_excluded_draft_ids" jsonb;
  ALTER TABLE "frameworks" ADD COLUMN "human_approval_publication_scope_deployment_authorized" boolean;
  ALTER TABLE "frameworks" ADD COLUMN "human_approval_publication_scope_publication_authorized" boolean;
  ALTER TABLE "case_studies" ADD COLUMN "canonical_url" varchar;
  ALTER TABLE "case_studies" ADD COLUMN "human_approval_approval_timestamp" timestamp(3) with time zone;
  ALTER TABLE "case_studies" ADD COLUMN "human_approval_approver" varchar;
  ALTER TABLE "case_studies" ADD COLUMN "human_approval_approver_limitation" varchar;
  ALTER TABLE "case_studies" ADD COLUMN "human_approval_content_revision_hash" varchar;
  ALTER TABLE "case_studies" ADD COLUMN "human_approval_publication_revision_hash" varchar;
  ALTER TABLE "case_studies" ADD COLUMN "human_approval_supporting_approved_insight_ids" jsonb;
  ALTER TABLE "case_studies" ADD COLUMN "human_approval_validation_result_deterministic_hard_gates_passed" boolean;
  ALTER TABLE "case_studies" ADD COLUMN "human_approval_validation_result_semantic_quality_passed" boolean;
  ALTER TABLE "case_studies" ADD COLUMN "human_approval_validation_result_failure_codes" jsonb;
  ALTER TABLE "case_studies" ADD COLUMN "human_approval_publication_scope_approved_canonical_paths" jsonb;
  ALTER TABLE "case_studies" ADD COLUMN "human_approval_publication_scope_excluded_draft_ids" jsonb;
  ALTER TABLE "case_studies" ADD COLUMN "human_approval_publication_scope_deployment_authorized" boolean;
  ALTER TABLE "case_studies" ADD COLUMN "human_approval_publication_scope_publication_authorized" boolean;
  ALTER TABLE "faqs" ADD COLUMN "canonical_url" varchar;
  ALTER TABLE "faqs" ADD COLUMN "human_approval_approval_timestamp" timestamp(3) with time zone;
  ALTER TABLE "faqs" ADD COLUMN "human_approval_approver" varchar;
  ALTER TABLE "faqs" ADD COLUMN "human_approval_approver_limitation" varchar;
  ALTER TABLE "faqs" ADD COLUMN "human_approval_content_revision_hash" varchar;
  ALTER TABLE "faqs" ADD COLUMN "human_approval_publication_revision_hash" varchar;
  ALTER TABLE "faqs" ADD COLUMN "human_approval_supporting_approved_insight_ids" jsonb;
  ALTER TABLE "faqs" ADD COLUMN "human_approval_validation_result_deterministic_hard_gates_passed" boolean;
  ALTER TABLE "faqs" ADD COLUMN "human_approval_validation_result_semantic_quality_passed" boolean;
  ALTER TABLE "faqs" ADD COLUMN "human_approval_validation_result_failure_codes" jsonb;
  ALTER TABLE "faqs" ADD COLUMN "human_approval_publication_scope_approved_canonical_paths" jsonb;
  ALTER TABLE "faqs" ADD COLUMN "human_approval_publication_scope_excluded_draft_ids" jsonb;
  ALTER TABLE "faqs" ADD COLUMN "human_approval_publication_scope_deployment_authorized" boolean;
  ALTER TABLE "faqs" ADD COLUMN "human_approval_publication_scope_publication_authorized" boolean;
  ALTER TABLE "glossary_terms" ADD COLUMN "canonical_url" varchar;
  ALTER TABLE "glossary_terms" ADD COLUMN "human_approval_approval_timestamp" timestamp(3) with time zone;
  ALTER TABLE "glossary_terms" ADD COLUMN "human_approval_approver" varchar;
  ALTER TABLE "glossary_terms" ADD COLUMN "human_approval_approver_limitation" varchar;
  ALTER TABLE "glossary_terms" ADD COLUMN "human_approval_content_revision_hash" varchar;
  ALTER TABLE "glossary_terms" ADD COLUMN "human_approval_publication_revision_hash" varchar;
  ALTER TABLE "glossary_terms" ADD COLUMN "human_approval_supporting_approved_insight_ids" jsonb;
  ALTER TABLE "glossary_terms" ADD COLUMN "human_approval_validation_result_deterministic_hard_gates_passed" boolean;
  ALTER TABLE "glossary_terms" ADD COLUMN "human_approval_validation_result_semantic_quality_passed" boolean;
  ALTER TABLE "glossary_terms" ADD COLUMN "human_approval_validation_result_failure_codes" jsonb;
  ALTER TABLE "glossary_terms" ADD COLUMN "human_approval_publication_scope_approved_canonical_paths" jsonb;
  ALTER TABLE "glossary_terms" ADD COLUMN "human_approval_publication_scope_excluded_draft_ids" jsonb;
  ALTER TABLE "glossary_terms" ADD COLUMN "human_approval_publication_scope_deployment_authorized" boolean;
  ALTER TABLE "glossary_terms" ADD COLUMN "human_approval_publication_scope_publication_authorized" boolean;
  ALTER TABLE "lead_magnets" ADD COLUMN "canonical_url" varchar;
  ALTER TABLE "lead_magnets" ADD COLUMN "human_approval_approval_timestamp" timestamp(3) with time zone;
  ALTER TABLE "lead_magnets" ADD COLUMN "human_approval_approver" varchar;
  ALTER TABLE "lead_magnets" ADD COLUMN "human_approval_approver_limitation" varchar;
  ALTER TABLE "lead_magnets" ADD COLUMN "human_approval_content_revision_hash" varchar;
  ALTER TABLE "lead_magnets" ADD COLUMN "human_approval_publication_revision_hash" varchar;
  ALTER TABLE "lead_magnets" ADD COLUMN "human_approval_supporting_approved_insight_ids" jsonb;
  ALTER TABLE "lead_magnets" ADD COLUMN "human_approval_validation_result_deterministic_hard_gates_passed" boolean;
  ALTER TABLE "lead_magnets" ADD COLUMN "human_approval_validation_result_semantic_quality_passed" boolean;
  ALTER TABLE "lead_magnets" ADD COLUMN "human_approval_validation_result_failure_codes" jsonb;
  ALTER TABLE "lead_magnets" ADD COLUMN "human_approval_publication_scope_approved_canonical_paths" jsonb;
  ALTER TABLE "lead_magnets" ADD COLUMN "human_approval_publication_scope_excluded_draft_ids" jsonb;
  ALTER TABLE "lead_magnets" ADD COLUMN "human_approval_publication_scope_deployment_authorized" boolean;
  ALTER TABLE "lead_magnets" ADD COLUMN "human_approval_publication_scope_publication_authorized" boolean;
  ALTER TABLE "problem_pages" ADD COLUMN "canonical_url" varchar;
  ALTER TABLE "problem_pages" ADD COLUMN "human_approval_approval_timestamp" timestamp(3) with time zone;
  ALTER TABLE "problem_pages" ADD COLUMN "human_approval_approver" varchar;
  ALTER TABLE "problem_pages" ADD COLUMN "human_approval_approver_limitation" varchar;
  ALTER TABLE "problem_pages" ADD COLUMN "human_approval_content_revision_hash" varchar;
  ALTER TABLE "problem_pages" ADD COLUMN "human_approval_publication_revision_hash" varchar;
  ALTER TABLE "problem_pages" ADD COLUMN "human_approval_supporting_approved_insight_ids" jsonb;
  ALTER TABLE "problem_pages" ADD COLUMN "human_approval_validation_result_deterministic_hard_gates_passed" boolean;
  ALTER TABLE "problem_pages" ADD COLUMN "human_approval_validation_result_semantic_quality_passed" boolean;
  ALTER TABLE "problem_pages" ADD COLUMN "human_approval_validation_result_failure_codes" jsonb;
  ALTER TABLE "problem_pages" ADD COLUMN "human_approval_publication_scope_approved_canonical_paths" jsonb;
  ALTER TABLE "problem_pages" ADD COLUMN "human_approval_publication_scope_excluded_draft_ids" jsonb;
  ALTER TABLE "problem_pages" ADD COLUMN "human_approval_publication_scope_deployment_authorized" boolean;
  ALTER TABLE "problem_pages" ADD COLUMN "human_approval_publication_scope_publication_authorized" boolean;
  ALTER TABLE "problem_pages" ADD COLUMN "published_at" timestamp(3) with time zone;
  CREATE INDEX "problem_pages_published_at_idx" ON "problem_pages" USING btree ("published_at");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP INDEX "problem_pages_published_at_idx";
  ALTER TABLE "entity_pages" DROP COLUMN "canonical_url";
  ALTER TABLE "entity_pages" DROP COLUMN "human_approval_approval_timestamp";
  ALTER TABLE "entity_pages" DROP COLUMN "human_approval_approver";
  ALTER TABLE "entity_pages" DROP COLUMN "human_approval_approver_limitation";
  ALTER TABLE "entity_pages" DROP COLUMN "human_approval_content_revision_hash";
  ALTER TABLE "entity_pages" DROP COLUMN "human_approval_publication_revision_hash";
  ALTER TABLE "entity_pages" DROP COLUMN "human_approval_supporting_approved_insight_ids";
  ALTER TABLE "entity_pages" DROP COLUMN "human_approval_validation_result_deterministic_hard_gates_passed";
  ALTER TABLE "entity_pages" DROP COLUMN "human_approval_validation_result_semantic_quality_passed";
  ALTER TABLE "entity_pages" DROP COLUMN "human_approval_validation_result_failure_codes";
  ALTER TABLE "entity_pages" DROP COLUMN "human_approval_publication_scope_approved_canonical_paths";
  ALTER TABLE "entity_pages" DROP COLUMN "human_approval_publication_scope_excluded_draft_ids";
  ALTER TABLE "entity_pages" DROP COLUMN "human_approval_publication_scope_deployment_authorized";
  ALTER TABLE "entity_pages" DROP COLUMN "human_approval_publication_scope_publication_authorized";
  ALTER TABLE "pillar_pages" DROP COLUMN "canonical_url";
  ALTER TABLE "pillar_pages" DROP COLUMN "human_approval_approval_timestamp";
  ALTER TABLE "pillar_pages" DROP COLUMN "human_approval_approver";
  ALTER TABLE "pillar_pages" DROP COLUMN "human_approval_approver_limitation";
  ALTER TABLE "pillar_pages" DROP COLUMN "human_approval_content_revision_hash";
  ALTER TABLE "pillar_pages" DROP COLUMN "human_approval_publication_revision_hash";
  ALTER TABLE "pillar_pages" DROP COLUMN "human_approval_supporting_approved_insight_ids";
  ALTER TABLE "pillar_pages" DROP COLUMN "human_approval_validation_result_deterministic_hard_gates_passed";
  ALTER TABLE "pillar_pages" DROP COLUMN "human_approval_validation_result_semantic_quality_passed";
  ALTER TABLE "pillar_pages" DROP COLUMN "human_approval_validation_result_failure_codes";
  ALTER TABLE "pillar_pages" DROP COLUMN "human_approval_publication_scope_approved_canonical_paths";
  ALTER TABLE "pillar_pages" DROP COLUMN "human_approval_publication_scope_excluded_draft_ids";
  ALTER TABLE "pillar_pages" DROP COLUMN "human_approval_publication_scope_deployment_authorized";
  ALTER TABLE "pillar_pages" DROP COLUMN "human_approval_publication_scope_publication_authorized";
  ALTER TABLE "cluster_pages" DROP COLUMN "canonical_url";
  ALTER TABLE "cluster_pages" DROP COLUMN "human_approval_approval_timestamp";
  ALTER TABLE "cluster_pages" DROP COLUMN "human_approval_approver";
  ALTER TABLE "cluster_pages" DROP COLUMN "human_approval_approver_limitation";
  ALTER TABLE "cluster_pages" DROP COLUMN "human_approval_content_revision_hash";
  ALTER TABLE "cluster_pages" DROP COLUMN "human_approval_publication_revision_hash";
  ALTER TABLE "cluster_pages" DROP COLUMN "human_approval_supporting_approved_insight_ids";
  ALTER TABLE "cluster_pages" DROP COLUMN "human_approval_validation_result_deterministic_hard_gates_passed";
  ALTER TABLE "cluster_pages" DROP COLUMN "human_approval_validation_result_semantic_quality_passed";
  ALTER TABLE "cluster_pages" DROP COLUMN "human_approval_validation_result_failure_codes";
  ALTER TABLE "cluster_pages" DROP COLUMN "human_approval_publication_scope_approved_canonical_paths";
  ALTER TABLE "cluster_pages" DROP COLUMN "human_approval_publication_scope_excluded_draft_ids";
  ALTER TABLE "cluster_pages" DROP COLUMN "human_approval_publication_scope_deployment_authorized";
  ALTER TABLE "cluster_pages" DROP COLUMN "human_approval_publication_scope_publication_authorized";
  ALTER TABLE "frameworks" DROP COLUMN "canonical_url";
  ALTER TABLE "frameworks" DROP COLUMN "human_approval_approval_timestamp";
  ALTER TABLE "frameworks" DROP COLUMN "human_approval_approver";
  ALTER TABLE "frameworks" DROP COLUMN "human_approval_approver_limitation";
  ALTER TABLE "frameworks" DROP COLUMN "human_approval_content_revision_hash";
  ALTER TABLE "frameworks" DROP COLUMN "human_approval_publication_revision_hash";
  ALTER TABLE "frameworks" DROP COLUMN "human_approval_supporting_approved_insight_ids";
  ALTER TABLE "frameworks" DROP COLUMN "human_approval_validation_result_deterministic_hard_gates_passed";
  ALTER TABLE "frameworks" DROP COLUMN "human_approval_validation_result_semantic_quality_passed";
  ALTER TABLE "frameworks" DROP COLUMN "human_approval_validation_result_failure_codes";
  ALTER TABLE "frameworks" DROP COLUMN "human_approval_publication_scope_approved_canonical_paths";
  ALTER TABLE "frameworks" DROP COLUMN "human_approval_publication_scope_excluded_draft_ids";
  ALTER TABLE "frameworks" DROP COLUMN "human_approval_publication_scope_deployment_authorized";
  ALTER TABLE "frameworks" DROP COLUMN "human_approval_publication_scope_publication_authorized";
  ALTER TABLE "case_studies" DROP COLUMN "canonical_url";
  ALTER TABLE "case_studies" DROP COLUMN "human_approval_approval_timestamp";
  ALTER TABLE "case_studies" DROP COLUMN "human_approval_approver";
  ALTER TABLE "case_studies" DROP COLUMN "human_approval_approver_limitation";
  ALTER TABLE "case_studies" DROP COLUMN "human_approval_content_revision_hash";
  ALTER TABLE "case_studies" DROP COLUMN "human_approval_publication_revision_hash";
  ALTER TABLE "case_studies" DROP COLUMN "human_approval_supporting_approved_insight_ids";
  ALTER TABLE "case_studies" DROP COLUMN "human_approval_validation_result_deterministic_hard_gates_passed";
  ALTER TABLE "case_studies" DROP COLUMN "human_approval_validation_result_semantic_quality_passed";
  ALTER TABLE "case_studies" DROP COLUMN "human_approval_validation_result_failure_codes";
  ALTER TABLE "case_studies" DROP COLUMN "human_approval_publication_scope_approved_canonical_paths";
  ALTER TABLE "case_studies" DROP COLUMN "human_approval_publication_scope_excluded_draft_ids";
  ALTER TABLE "case_studies" DROP COLUMN "human_approval_publication_scope_deployment_authorized";
  ALTER TABLE "case_studies" DROP COLUMN "human_approval_publication_scope_publication_authorized";
  ALTER TABLE "faqs" DROP COLUMN "canonical_url";
  ALTER TABLE "faqs" DROP COLUMN "human_approval_approval_timestamp";
  ALTER TABLE "faqs" DROP COLUMN "human_approval_approver";
  ALTER TABLE "faqs" DROP COLUMN "human_approval_approver_limitation";
  ALTER TABLE "faqs" DROP COLUMN "human_approval_content_revision_hash";
  ALTER TABLE "faqs" DROP COLUMN "human_approval_publication_revision_hash";
  ALTER TABLE "faqs" DROP COLUMN "human_approval_supporting_approved_insight_ids";
  ALTER TABLE "faqs" DROP COLUMN "human_approval_validation_result_deterministic_hard_gates_passed";
  ALTER TABLE "faqs" DROP COLUMN "human_approval_validation_result_semantic_quality_passed";
  ALTER TABLE "faqs" DROP COLUMN "human_approval_validation_result_failure_codes";
  ALTER TABLE "faqs" DROP COLUMN "human_approval_publication_scope_approved_canonical_paths";
  ALTER TABLE "faqs" DROP COLUMN "human_approval_publication_scope_excluded_draft_ids";
  ALTER TABLE "faqs" DROP COLUMN "human_approval_publication_scope_deployment_authorized";
  ALTER TABLE "faqs" DROP COLUMN "human_approval_publication_scope_publication_authorized";
  ALTER TABLE "glossary_terms" DROP COLUMN "canonical_url";
  ALTER TABLE "glossary_terms" DROP COLUMN "human_approval_approval_timestamp";
  ALTER TABLE "glossary_terms" DROP COLUMN "human_approval_approver";
  ALTER TABLE "glossary_terms" DROP COLUMN "human_approval_approver_limitation";
  ALTER TABLE "glossary_terms" DROP COLUMN "human_approval_content_revision_hash";
  ALTER TABLE "glossary_terms" DROP COLUMN "human_approval_publication_revision_hash";
  ALTER TABLE "glossary_terms" DROP COLUMN "human_approval_supporting_approved_insight_ids";
  ALTER TABLE "glossary_terms" DROP COLUMN "human_approval_validation_result_deterministic_hard_gates_passed";
  ALTER TABLE "glossary_terms" DROP COLUMN "human_approval_validation_result_semantic_quality_passed";
  ALTER TABLE "glossary_terms" DROP COLUMN "human_approval_validation_result_failure_codes";
  ALTER TABLE "glossary_terms" DROP COLUMN "human_approval_publication_scope_approved_canonical_paths";
  ALTER TABLE "glossary_terms" DROP COLUMN "human_approval_publication_scope_excluded_draft_ids";
  ALTER TABLE "glossary_terms" DROP COLUMN "human_approval_publication_scope_deployment_authorized";
  ALTER TABLE "glossary_terms" DROP COLUMN "human_approval_publication_scope_publication_authorized";
  ALTER TABLE "lead_magnets" DROP COLUMN "canonical_url";
  ALTER TABLE "lead_magnets" DROP COLUMN "human_approval_approval_timestamp";
  ALTER TABLE "lead_magnets" DROP COLUMN "human_approval_approver";
  ALTER TABLE "lead_magnets" DROP COLUMN "human_approval_approver_limitation";
  ALTER TABLE "lead_magnets" DROP COLUMN "human_approval_content_revision_hash";
  ALTER TABLE "lead_magnets" DROP COLUMN "human_approval_publication_revision_hash";
  ALTER TABLE "lead_magnets" DROP COLUMN "human_approval_supporting_approved_insight_ids";
  ALTER TABLE "lead_magnets" DROP COLUMN "human_approval_validation_result_deterministic_hard_gates_passed";
  ALTER TABLE "lead_magnets" DROP COLUMN "human_approval_validation_result_semantic_quality_passed";
  ALTER TABLE "lead_magnets" DROP COLUMN "human_approval_validation_result_failure_codes";
  ALTER TABLE "lead_magnets" DROP COLUMN "human_approval_publication_scope_approved_canonical_paths";
  ALTER TABLE "lead_magnets" DROP COLUMN "human_approval_publication_scope_excluded_draft_ids";
  ALTER TABLE "lead_magnets" DROP COLUMN "human_approval_publication_scope_deployment_authorized";
  ALTER TABLE "lead_magnets" DROP COLUMN "human_approval_publication_scope_publication_authorized";
  ALTER TABLE "problem_pages" DROP COLUMN "canonical_url";
  ALTER TABLE "problem_pages" DROP COLUMN "human_approval_approval_timestamp";
  ALTER TABLE "problem_pages" DROP COLUMN "human_approval_approver";
  ALTER TABLE "problem_pages" DROP COLUMN "human_approval_approver_limitation";
  ALTER TABLE "problem_pages" DROP COLUMN "human_approval_content_revision_hash";
  ALTER TABLE "problem_pages" DROP COLUMN "human_approval_publication_revision_hash";
  ALTER TABLE "problem_pages" DROP COLUMN "human_approval_supporting_approved_insight_ids";
  ALTER TABLE "problem_pages" DROP COLUMN "human_approval_validation_result_deterministic_hard_gates_passed";
  ALTER TABLE "problem_pages" DROP COLUMN "human_approval_validation_result_semantic_quality_passed";
  ALTER TABLE "problem_pages" DROP COLUMN "human_approval_validation_result_failure_codes";
  ALTER TABLE "problem_pages" DROP COLUMN "human_approval_publication_scope_approved_canonical_paths";
  ALTER TABLE "problem_pages" DROP COLUMN "human_approval_publication_scope_excluded_draft_ids";
  ALTER TABLE "problem_pages" DROP COLUMN "human_approval_publication_scope_deployment_authorized";
  ALTER TABLE "problem_pages" DROP COLUMN "human_approval_publication_scope_publication_authorized";
  ALTER TABLE "problem_pages" DROP COLUMN "published_at";`)
}
