import Link from "next/link";
import Image from "next/image";
import type { Metadata } from "next";
import { HomeV3Selector } from "@/components/home-v3-selector";
import { HomeV3TrackedLink } from "@/components/home-v3-tracked-link";

export const metadata: Metadata = {
  title: "Technical Leadership Coaching for Engineering Managers & Directors | The Push",
  description: "12-week 1:1 technical leadership coaching for Engineering Managers, Group Managers and Directors in growing B2B SaaS companies who are still the path for too many decisions, reviews and escalations.",
  alternates: { canonical: "https://itayfoyerstein.com/" },
  robots: { index: true, follow: true },
};

const scenes = [["The meeting you have to attend.", "You are accountable for the outcome, so being informed quietly turned into being present."], ["The decision that comes back for one last check.", "The team can do the work, but judgment still lives one level higher."], ["The strategic work that starts after meetings end.", "Delivery is moving. Your calendar is full. The work only you should do gets pushed to later."]];
const steps = [["01", "Start with what actually happened.", "Who was involved? What decision, review or escalation came back?"], ["02", "Test competing explanations.", "Unclear authority? Missing context or judgment? Capability not ready? Or involvement genuinely justified by risk?"], ["03", "Run one reversible experiment.", "Change one boundary, review, escalation rule or meeting, not the entire organization."], ["04", "Inspect what came back.", "The evidence from the next cycle decides whether to continue, change the hypothesis or stop."]];
const proofCases = [["Avi · senior R&D leader", "Calendar overload → control", "An overloaded calendar and reactive meetings became a question of which meetings required a decision, what he needed to ask for, and where his presence was unnecessary. He moved toward a more controlled schedule, dedicated 1:1 planning time, and a clearer operating plan for his team and attention."], ["Itay · product / engineering leader", "30 min", "He believed he needed to attend because the feature was his responsibility. He tested whether any decision actually required him. It did not. The meeting disappeared; accountability did not."], ["Claudia · senior commercial leader", "Operating at $10M–$20M sales-plan scope", "Four to six escalation meetings a day sat alongside planning around a $10M sales plan and continued work around a $20M sales plan. The work distinguished valuable senior judgment from learned dependency. These figures describe commercial scope, not revenue attributed to The Push."]];

export default function HomePage() {
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "WebPage", "@id": "https://itayfoyerstein.com/", "url": "https://itayfoyerstein.com/", "name": "Technical Leadership Coaching for Engineering Managers & Directors | The Push", "description": metadata.description }, { "@type": "Person", "name": "Itay Foyerstein", "url": "https://itayfoyerstein.com/about", "jobTitle": "Technical leadership coach" }, { "@type": "ProfessionalService", "name": "The Push", "url": "https://itayfoyerstein.com/entities/the-push", "serviceType": "Technical leadership coaching", "provider": { "@type": "Person", "name": "Itay Foyerstein" } }] };
  return <main className="home-v3" id="top">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <nav className="v3-local-nav" aria-label="Homepage sections"><Link href="#proof">Proof</Link><Link href="#how-it-works">How it works</Link><Link href="#fit">Fit</Link><Link href="#about-itay">About Itay</Link><Link className="v3-nav-cta" href="#diagnostic">Bring one case</Link></nav>
    <section className="v3-hero"><div><p className="v3-eyebrow">Technical leadership coaching</p><h1>Stop being<br />the system.</h1><div className="v3-hero-image"><Image src="/itay-home-photo.jpg" alt="Itay Foyerstein, technical leadership coach" width={896} height={1195} priority /></div></div><div className="v3-hero-copy"><p>Your team can execute. But the hard decisions, reviews and escalations still come back to you. <strong>The Push helps you change that without stepping away from the work that actually needs your judgment.</strong></p><div className="v3-actions"><HomeV3TrackedLink className="v3-primary">Bring one current case →</HomeV3TrackedLink><Link className="v3-button" href="#work">See the engagement</Link></div><small>Engineering Managers · Group Managers · Directors<br />Growing B2B SaaS · typically 50–250 people<br />12 weeks · 6 private 1:1 sessions</small></div></section>
    <section className="v3-strip"><div><b>Recognition</b><p>Capable team. Too much still routes through you.</p></div>{scenes.map(([title, body]) => <div key={title}><b>{title}</b><p>{body}</p></div>)}</section>
    <section className="v3-section v3-dark" id="proof"><div className="v3-two"><div><p className="v3-eyebrow">Observed in real work</p><blockquote>“I’m more precise. I know better what I want to ask. I cut meetings faster.”<cite>Avi · senior R&amp;D leader</cite></blockquote></div><div><h2>Evidence from situations we worked on.</h2><p>Each case starts with a live incident, tests competing explanations, and looks for what changes. These are examples of the work, not promises of a universal outcome.</p><div className="v3-cards">{proofCases.map(([name, title, body]) => <article key={name}><b>{title}</b><span>{body}</span><small>{name}</small></article>)}</div></div></div></section>
    <section className="v3-section" id="how-it-works"><p className="v3-eyebrow">How I work</p><div className="v3-two"><h2>Do not call it a bottleneck before the evidence earns the diagnosis.</h2><p>One incident is a story. A repeated pattern, competing explanations and a reversible test give us something useful. The explanations may be authority, context and judgment, capability, or genuine risk and constraint.</p></div><div className="v3-presence-test"><b>Presence Test</b><span>What decision cannot be made if I am not there?</span></div><div className="v3-steps">{steps.map(([n, title, body]) => <article key={n}><small>{n}</small><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <HomeV3Selector />
    <section className="v3-section v3-paper" id="work"><p className="v3-eyebrow">The engagement</p><div className="v3-two"><h2>One live leadership problem. Six cycles of diagnosis, action and evidence.</h2><p>The Push is a 12-week 1:1 coaching and advisory engagement. We work on the real decisions, people, meetings and constraints in your role, not a generic leadership curriculum.</p></div><div className="v3-cards v3-offer"><article><b>12 weeks</b><span>Enough time to observe patterns and test behavior in real work.</span></article><article><b>6 private 1:1 sessions</b><span>Six biweekly sessions built around the live problem.</span></article><article><b>Example outputs</b><span>Decision map, bottleneck tracker, stakeholder map, or 30/60/90 plan may emerge from the work.</span></article></div></section>
    <section className="v3-section" id="fit"><p className="v3-eyebrow">Fit</p><div className="v3-two"><h2>Sometimes coaching is not the answer.</h2><p>If the real constraint sits in the organization rather than in how you are operating, the useful move is to name that clearly.</p></div><div className="v3-fit"><article><h3>Strong fit</h3><ul><li>Your scope grew but judgment still routes upward.</li><li>You lead capable people, manage managers, or are growing a leadership layer.</li><li>You are willing to test changes between sessions.</li></ul></article><article><h3>Probably not a coaching problem</h3><ul><li>You do not have the authority the role requires.</li><li>The team is materially understaffed or has a specialist technical gap.</li><li>Organization design is unresolved; hiring or training is the better intervention.</li></ul></article></div></section>
    <section className="v3-section v3-about" id="about-itay"><div className="v3-two"><div><p className="v3-eyebrow">About Itay</p><Image src="/itay-home-photo.jpg" alt="Itay Foyerstein" width={896} height={1195} /></div><div><h2>Practice built across the system around the leader.</h2><p>25+ years and 1000+ coaching hours across technology, product, delivery, consulting and organizational change.</p><p>Across that career, I have worked with teams and organizations including ServiceNow, Amdocs, Taboola, Claroty, EY, 888 and others. This is career context, not a claim that each organization purchased The Push.</p><Link className="v3-button" href="/about">Read about Itay →</Link></div></div></section>
    <section className="v3-section v3-dark" id="diagnostic-cta"><div className="v3-two"><div><p className="v3-eyebrow">Start with your case</p><h2>Get something useful before you book anything.</h2></div><div><p>Bring one current decision, review, escalation or meeting that keeps coming back to you. The diagnostic returns an observed pattern, likely explanation, evidence against it, one reversible experiment, and a next step.</p><Link className="v3-primary" href="#diagnostic">Start with my case →</Link></div></div></section>
    <footer className="v3-home-footer"><Link href="#top">The Push</Link><span>Technical leadership coaching for engineering leaders.</span><Link href="/contact">Contact</Link></footer>
  </main>;
}
